# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: minimal

cache:
  cargo: true
  directories:
    - $HOME/build/darwinia-network/darwinia/node/runtime/wasm/target/wasm32-unknown-unknown/release

branches:
  only:
    - master

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  # Check how much space we've got on this machine.
  - df -h
  - ls $HOME/build/darwinia-network/darwinia/node/runtime/wasm/target/wasm32-unknown-unknown/release

jobs:
  include:
    - stage: Install
      script: ./ci/script.sh nightly wasm
    - stage: Test
      script: ./ci/script.sh stable native

after_script:
  # Check how much free disk space left after the build
  - df -h